### ISSUE TITLE
Qt/5.11.1 cant be installed if 32 and 64bit libraries are installed

### ISSUE THREAD

**Issue by nolange** [bincrafters/community#452]
### Description of Problem, Request, or Question
Plainly using "Qt/5.11.1@bincrafters/stable" will fail on conan install

### Package Details (Include if Applicable)
* Package Name/Version: **zstd/1.3.3**
* Operating System: **Linux Debian Buster**
* Conan Version: 1.7.4

### Steps to reproduce (Include if Applicable)

Install a dependent package for 64 and 32 bit.
```bash
dpkg --add-architecture i386
apt-get update
apt-get install libxcb1 libxcb1:i386
```
Use the [new_project_template](https://github.com/mpusz/new_project_template),
add `Qt/5.11.1@bincrafters/stable`  as dependency.

try to install the dependencies:
```bash
mkdir build
cd build
conan install ..
```

That will fail on the command `dpkg-query --status libxcb1`, see log below.
Additionally: I really dont want conan to even try to sudo, wont work and should just fail (like on buildservers)

```
Qt/5.11.1@bincrafters/stable: Not found in local cache, looking in remotes...
Qt/5.11.1@bincrafters/stable: Trying with 'conan-center'...
Qt/5.11.1@bincrafters/stable: Trying with 'bincrafters'...
Downloading conanmanifest.txt
[==================================================] 392B/392B        
Downloading conanfile.py
[==================================================] 13.4KB/13.4KB    
Downloading conan_export.tgz
[==================================================] 4.2KB/4.2KB      
Downloading conaninfo.txt
[==================================================] 494B/494B        
Downloading conaninfo.txt

PROJECT: Installing /home/noppl/git/new_project_template-master/conanfile.py
Requirements
Packages
Build requirements
    Qt/5.11.1@bincrafters/stable from 'bincrafters' - Downloaded
    gtest/1.8.0@bincrafters/stable from 'conan-center' - Cache
Build requirements packages
    Qt/5.11.1@bincrafters/stable:0f4662410f0a9bdf85201fd748f5a42c05d1f5a4 - Download
    gtest/1.8.0@bincrafters/stable:eea471029afd178285a9408339b804914029020f - Download

Qt/5.11.1@bincrafters/stable: Retrieving package 0f4662410f0a9bdf85201fd748f5a42c05d1f5a4 from remote 'bincrafters' 
Downloading conanmanifest.txt
[==================================================] 236.0KB/236.0KB  
Downloading conaninfo.txt
[==================================================] 2.4KB/2.4KB      
Downloading conan_package.tgz
[==================================================] 29.7MB/29.7MB    
Qt/5.11.1@bincrafters/stable: Package installed 0f4662410f0a9bdf85201fd748f5a42c05d1f5a4
dpkg-query: error: --status needs a valid package name but 'libxcb1' is not: ambiguous package name 'libxcb1' with more than one installed instance

Use --help for help about querying packages.
Running: sudo apt-get update
[sudo] password for XXX: 
XXX is not in the sudoers file.  This incident will be reported.
Qt/5.11.1@bincrafters/stable: ERROR: while executing system_requirements(): Command 'sudo apt-get update' failed
ERROR: Error in system requirements
```

PS. This is my very first attempt at using conan, might be that this is a bug/deficiency from conan itself.

**Comment by ericLemanissier** [comment]
It seems reasonable. I just pushed a quick fix to the recipe, explicating the architecture of system packages. Can you please tell me if it solves the issue for you?
for your remark about sudo, please refer to https://docs.conan.io/en/latest/reference/env_vars.html?highlight=conan_sysrequires_sudo#conan-sysrequires-sudo

**Comment by nolange** [comment]
I guess I need to build QT from source to test the fix?
I am also not sure, if replicating every architecture is a good thing - this will fail if I want to cross-build for arm then, or if I have a different rootfs for the target (like an embedded system) and would need to use the libxcb1 from there !?

That logic seems to focus on the system I am building on, not the one I am targeting.

**Comment by ericLemanissier** [comment]
You can simply remove the qt recipe from your local cache and retry the steps you reported in your first message.
self.settings is the target so we select the package architecture based on the target. On the other hand we use also `tools.os_info` (which refers to the building system) to decide which package to install, so in the cross compilation case the recipe installs some packages which are not actually used. That said I heard several users having success with cross compilation. Maybe the necessary packages were already installed? Anyway please tell us if you notice any other problem.

**Comment by nolange** [comment]
Ok, that fixes the issue, thanks.
But I still dont get why I need all these libraries? especially libgl1-mesa**-dev** should not be needed unless qt is compiled from source.

**Comment by ericLemanissier** [comment]
Indeed, the *-dev package should only be installed when building from source. Do you have a log which shows the installation of *-dev when existing binaries are reused ?

**Comment by nolange** [comment]
sure
```
$ CONAN_SYSREQUIRES_SUDO=0 ~/.local/bin/conan install  ..
Qt/5.11.1@bincrafters/stable: Retrieving from predefined remote 'bincrafters'
Qt/5.11.1@bincrafters/stable: Trying with 'bincrafters'...
Downloading conanmanifest.txt
[==================================================] 392B/392B        
Downloading conanfile.py
[==================================================] 13.6KB/13.6KB    
Downloading conan_export.tgz
[==================================================] 4.2KB/4.2KB      
Downloading conaninfo.txt

PROJECT: Installing /home/noppl/git/new_project_template-master/conanfile.py
Requirements
Packages
Build requirements
    Qt/5.11.1@bincrafters/stable from 'bincrafters' - Downloaded
    gtest/1.8.0@bincrafters/stable from 'conan-center' - Cache
Build requirements packages
    Qt/5.11.1@bincrafters/stable:0f4662410f0a9bdf85201fd748f5a42c05d1f5a4 - Download
    gtest/1.8.0@bincrafters/stable:eea471029afd178285a9408339b804914029020f - Cache

Qt/5.11.1@bincrafters/stable: Retrieving package 0f4662410f0a9bdf85201fd748f5a42c05d1f5a4 from remote 'bincrafters' 
Downloading conanmanifest.txt
[==================================================] 236.0KB/236.0KB  
Downloading conaninfo.txt
[==================================================] 2.4KB/2.4KB      
Downloading conan_package.tgz
[==================================================] 29.7MB/29.7MB    
Qt/5.11.1@bincrafters/stable: Package installed 0f4662410f0a9bdf85201fd748f5a42c05d1f5a4
Package: libxcb1
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 290
Maintainer: Debian X Strike Force <debian-x@lists.debian.org>
Architecture: amd64
Multi-Arch: same
Source: libxcb
Version: 1.13-3
Depends: libc6 (>= 2.14), libxau6, libxdmcp6
Breaks: alsa-utils (<< 1.0.24.2-5)
Description: X C Binding
 This package contains the library files needed to run software using libxcb,
 the X C Binding.
 .
 The XCB library provides an interface to the X Window System protocol,
 designed to replace the Xlib interface.  XCB provides several advantages over
 Xlib:
 .
  * Size: small library and lower memory footprint
  * Latency hiding: batch several requests and wait for the replies later
  * Direct protocol access: one-to-one mapping between interface and protocol
  * Thread support: access XCB from multiple threads, with no explicit locking
  * Easy creation of new extensions: automatically generates interface from
    machine-parsable protocol descriptions
Homepage: https://xcb.freedesktop.org

Package: libx11-6
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 1555
Maintainer: Debian X Strike Force <debian-x@lists.debian.org>
Architecture: amd64
Multi-Arch: same
Source: libx11
Version: 2:1.6.6-1
Depends: libc6 (>= 2.15), libxcb1 (>= 1.11.1), libx11-data
Description: X11 client-side library
 This package provides a client interface to the X Window System, otherwise
 known as 'Xlib'.  It provides a complete API for the basic functions of the
 window system.
 .
 More information about X.Org can be found at:
 <URL:https://www.X.org>
 .
 This module can be found at
 git://anongit.freedesktop.org/git/xorg/lib/libX11

dpkg-query: package 'libgl1-mesa-dev' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
Running: apt-get update
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
Qt/5.11.1@bincrafters/stable: ERROR: while executing system_requirements(): Command 'apt-get update' failed
ERROR: Error in system requirements

```

**Comment by ericLemanissier** [comment]
My bad, libgl1-mesa-dev is actually needed to build qt applications, as specified http://doc.qt.io/qt-5/linux.html#requirements-for-development-host. It's not a bug!
