### ISSUE TITLE
portaudio/v190600.20161030@bincrafters/stable WASAPI support?

### ISSUE THREAD

**Issue by izzyreal** [bincrafters/community#742]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: portaudio/v190600.20161030@bincrafters/stable
  * Operating System+version: Windows 10.0.17763
  * Compiler+version: Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27030.1 for x64
  * Conan version: Conan 1.14.3
  * Python version: Python 3.7.3

### Question Description
Does this package support WASAPI in the given setting? If yes, how? I've added it to the requirements of one of 4 conan packages that make up a conan workspace that I'm building with Visual Studio Community 2017. I have a WASAPI device available (working in at least one other application), but `Pa_GetHostApiInfo(Pa_HostApiTypeIdToHostApiIndex(paWASAPI))` returns nullptr. Checking `Pa_GetHostApiInfo(i)` based on `Pa_GetHostApiCount()` lists MME, DS and WDM-KS, but no WASAPI.

**Comment by SSE4** [comment]
as I can see from build logs, it wasn't compiled: https://ci.appveyor.com/project/BinCrafters/conan-portaudio/build/job/n2krj5yiq1da52b2?fullLog=true
but `PA_USE_WASAPI` should be on by default (according to the https://app.assembla.com/spaces/portaudio/git/source/master/CMakeLists.txt#ln205)
need to debug a bit...

**Comment by SSE4** [comment]
okay, fixed at : https://github.com/bincrafters/conan-portaudio/commit/148ba46e87585f957bd0bea964d6f7da1267abed
issue was usage of macro `MSVS` instead of `MSVC` in their CMakeLists.txt

**Comment by izzyreal** [comment]
Supercool, I'll go back to portaudio then. Was trying qno's rtaudio for a bit, but I don't think it's as mature yet.

**Comment by izzyreal** [comment]
I don't think I understand how to apply this fix, or the fix doesn't work.

I've copied the `conanfile.py` contents from `148ba46` into `C:\Users\izmar\.conan\data\portaudio\v190600.20161030\bincrafters\stable\export\conanfile.py`, cleaned my workspace and editable packages, rebuilt everything and I'm still getting the same issue. Everything works fine with DirectSound but not WASAPI.

**Comment by SSE4** [comment]
@izzyreal could you provide your build log? does it contain `pa_win_wasapi.c`? appveyor currently builds it: https://ci.appveyor.com/project/bincrafters/conan-portaudio/build/job/s0kasg0tbclch0o9

**Comment by izzyreal** [comment]
@SSE4 If I pull and build `portaudio/v190600.20161030@bincrafters/stable`, `pa_win_wasapi.c` is not compiled. If I apply your fix, it is compiled. But I'm applying that one line of your fix from `testing` to my `stable`.

But my application is having trouble with the compiled result after I applied your fix in that way. My app logs show `901 [13884] ERROR root <> - Host API not found`, an error that comes from `portaudio`, even when I try to use directsound.

PA is behaving really weird on my setup somehow. Yesterday when I removed PA from my conan cache, just pull a fresh stable, I got rid of the API not found error. I tried that now after applying your fix from scratch and I still get that error.

Is there a remote where can pull PA testing from? I'm getting the feeling that might help.

**Comment by izzyreal** [comment]
And now it's working again. I really need to rebuild my whole project, not just the target that uses PA. I'll now see if that also works after compiling PA including the wasapi.c file.

**Comment by izzyreal** [comment]
Yeah, please let me know how to properly use that testing version. I don't think how I patch PA stable with that one line fix works well -- I get only one dir built in my conan cache's bincrafters/stable/package, rather than the 2 I get when just pulling PA stable and building as is.

**Comment by SSE4** [comment]
@izzyreal I am not sure, why do you need testing branch? it's for testing only, so never uploaded to the bintray. stable branch should be identical and contain all required changes.
if you still want to use testing, run the following commands:
```
git clone git@github.com:bincrafters/conan-portaudio.git --branch testing/v190600.20161030
cd conan-portaudio
conan create . bincrafters/testing
```
this should properly export everything needed...
but again, it's recommended to use stable going forward.

**Comment by izzyreal** [comment]
@SSE4 Ok, good to know. It's just that if I recall correctly the PA testing conanfile.py seemed to deviate from the stable one beyond that one line fix, but I will have to verify if that's really the case. When was the stable package on bintray last updated?

Please confirm that how I try your fix is correct. So I simply modify the PA stable conanfile.py in my .conan/data dir, only adding that one line from your fix. Then I rebuild my workspace, which includes cleaning the whole solution, and I rebuild the whole thing in VS.

**Comment by SSE4** [comment]
@izzyreal yeah it was different, but I've merged it, so now it should be absolutely identical.

your way of rebuilding is correct, should be fine for testing purposes.

**Comment by izzyreal** [comment]
@SSE4 Alrighty, everything works now :)

Not sure if it's got to do with anything, and I don't know when your fixing commit was uploaded to bintray, but I also removed the portaudio lines from `.conan/registry.json` this time. I confirmed `conanfile.py` is the same length as your fix and rebuilt my workspace.

WASAPI is working!
